#!/usr/bin/env python

import sys
from urllib.request import urlopen

if len(sys.argv) == 1:
    options = ['python']
    sys.exit(f"Possible options are: {', '.join(options)}.")

lang = sys.argv[1]

if lang.lower() == "python":

    url = "https://raw.githubusercontent.com/github/gitignore/master/Python.gitignore"
    response = urlopen(url)

    with open(".gitignore", "wb") as f:
        f.write(response.read())

    print(".gitignore file created.")
    sys.exit(0)


else:

    sys.exit(f"Error: .gitignore for '{lang}' does not exist.")
